schema_version: 1
workflows:
  - match:
      path: .github/workflows/CI.yaml
    profile: ci
  - match:
      path: .github/workflows/CI_full_matrix.yaml
    profile: ci
  - match:
      path: .github/workflows/build_and_upload_conda_packages.yaml
    profile: release
  - match:
      path: .github/workflows/docs_ci.yaml
    profile: docs
  - match:
      path: .github/workflows/qa_ci.yaml
    profile: ci
  - match:
      path: .github/workflows/sphinx_docs_to_gh_pages.yaml
    profile: docs
