package:
  name: smonitor
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../   # repo root

build:
  number: 1

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - versioningit >=3.0
  run:
    - python

about:
  home: "https://www.uibcdf.org"
  license: "MIT"
  summary: "Centralized diagnostic & telemetry system for the scientific Python stack"
  dev_url: https://www.github.com/uibcdf/smonitor
  doc_url: https://www.uibcdf.org/smonitor
