package:
  name: smonitor
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../   # repo root

build:
  number: "{{ environ.get('SMONITOR_CONDA_BUILD_NUMBER', '0') }}"
  noarch: python

requirements:
  host:
    - python >=3.11,<3.14
    - pip
    - setuptools >=61.0
    - versioningit >=3.0
  run:
    - python >=3.11,<3.14

test:
  imports:
    - smonitor
  commands:
    - smonitor --help

about:
  home: "https://www.uibcdf.org"
  license: "MIT"
  summary: "Centralized diagnostic & telemetry system for the scientific Python stack"
  dev_url: https://www.github.com/uibcdf/smonitor
  doc_url: https://www.uibcdf.org/smonitor
